version: 2.1
jobs:
    # The test job
    test:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run:
                name: Install local dependencies
                command: npm install
            - run:
                name: Testing
                command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI